### ISSUE TITLE
Unable to install Fifth

### ISSUE THREAD

**Issue by pepalogik** [clbr/fifth#12]
Hi,

I am happy that somebody (i.e. you) is working on an Opera <= 12 replacement, and I would like to try it out. Unfortunately, I am not able to install it.

Since the builds on sf.net seem a bit outdated, I wanted to build Fifth from source. I have installed all the dependencies. As FLTK >= 1.3.3 is required (according to your web site) and the most recent version available in Synaptic is 1.3.2-4, I downloaded and installed FLTK manually. And that probably causes the problem: pkg-config cannot see it. If I try to configure Fifth, it ends up with this:

```
checking for DEPS... yes
checking for CPPDEPS... no
configure: error: Package requirements (harfbuzz harfbuzz-icu icu-uc icu-i18n webkitfltk) were not met:

No package 'webkitfltk' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables CPPDEPS_CFLAGS
and CPPDEPS_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

I have even used fltk-config to find the gcc options and tried passing them to configure:

`CPPDEPS_CFLAGS='-I../fltk-1.3.3 -I../fltk-1.3.3/jpeg -I/usr/include/freetype2 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_THREAD_SAFE -D_REENTRANT' CPPDEPS_LIBS='-L../fltk-1.3.3/lib -lfltk -lXcursor -lXfixes -lXext -lXft -lfontconfig -lXinerama -lpthread -ldl -lm -lX11' ./configure`

Result:

(...)
```
checking for DEPS... yes
checking for CPPDEPS... yes
checking for webkitInit in -lwebkitfltk... no
configure: error: libwebkitfltk not found
```

What can I do to make it work?

**Comment by clbr** [comment]
Please build and install webkitFLTK first. Fifth is "just" the browser
candy, it needs the webkit engine to render pages.

Using git master for both webkitfltk and fifth is known to work, it's
what I run every day.

**Comment by pepalogik** [comment]
Thank you for your answer. Sorry, I did not understand from your download page <http://fifth-browser.sourceforge.net/downloads.html> that WebkitFLTK is a Fifth's dependency, and there is even no link to WebkitFLTK (GitHub). Perhaps you should make the download page clearer for potential users. (I thought the configure error resulted from pkg-config not seeing FLTK.)

BTW, here is a warning from building WTF:
```
fltk/RunLoopFLTK.cpp: In member function ‘bool WTF::RunLoop::TimerBase::isActive() const’:
fltk/RunLoopFLTK.cpp:122:1: warning: no return statement in function returning non-void [-Wreturn-type]
 }
 ^
```

After the hours of making WebkitFLTK (especially WebCore), I am stuck on a WebKit/fltk testapp building error:
```
/tmp/libwebkitfltk.a: error adding symbols: No more archived files
collect2: error: ld returned 1 exit status
make: *** [testapp/testapp] Error 1
make: Leaving directory `/home/jenda/SW/webkitfltk-fltk/Source/WebKit/fltk'
```

First I got an "incomplete file" error because of lack of space in /tmp, so I thought this second error was some after-effect, but then I freed enough space, did `make -C Source/WebKit/fltk clean` and even manually deleted /tmp/libwebkitfltk.a and still I am getting the same error. Although I have studied the makefile, I have no clue what the cause can be (I was suspecting a backslash but that wasn't it). Google has no results for "error adding symbols: No more archived files", which is really strange. libwebkitfltk.a file size is 391 MiB, so I think it does contain the files.

Any suggestion?

**Comment by pepalogik** [comment]
Sorry, my fault. /home also had too little free space for the stuff.

**Comment by clbr** [comment]
Can this be closed, or?

**Comment by pepalogik** [comment]
Yes, it can, Fifth finally works for me. I have also noticed that you modified the download page. However, I suggest also providing the direct link <https://github.com/clbr/webkitfltk>.
