### ISSUE TITLE
configure error with liburlmatch

### ISSUE THREAD

**Issue by sergiall** [clbr/fifth#20]
Hello, I'm trying to configure & install the fifth on my ubuntu 16.04,but then I do 
`./autogen && ./configure --prefix=/opt`
 I get this error 
`
checking for PTHREAD_PRIO_INHERIT... yes
checking for fltk-config13... no
checking for fltk-config... fltk-config
checking for url_init in -lurlmatch... no
configure: error: liburlmatch not found
`
but I'm compile and install the liburlmatch
`
git clone https://github.com/clbr/urlmatch;cd urlmatch;make all && sudo make install
`
How to resolve this error?

**Comment by clbr** [comment]
Did urlmatch build successfully? Does /usr/lib/liburlmatch.a exist, and
if so, what does "nm /usr/lib/liburlmatch.a | grep init" say?

**Comment by sergiall** [comment]
Yes,liburlmatch was successfully build and liburlmatch.a was installed in /usr/lib.Now I  type in build folder your command and get this
`
nm /usr/lib/liburlmatch.a | grep init
opti_init.o:
000002c0 T url_init
00000c70 T url_init_file
00000940 T url_init_file2
`

**Comment by sergiall** [comment]
I'm found this section of code in generated 'configure' file

# Checks for libraries.
OLD_LDFLAGS=$LDFLAGS
LDFLAGS="$LDFLAGS -lz"
{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for url_init in -lurlmatch" >&5
$as_echo_n "checking for url_init in -lurlmatch... " >&6; }
if ${ac_cv_lib_urlmatch_url_init+:} false; then :
  $as_echo_n "(cached) " >&6
else
  ac_check_lib_save_LIBS=$LIBS
LIBS="-lurlmatch  $LIBS"
cat confdefs.h - <<_ACEOF >conftest.$ac_ext
/* end confdefs.h.  */

/* Override any GCC internal prototype to avoid an error.
   Use char because int might match the return type of a GCC
   builtin and then its argument prototype would still apply.  */
#ifdef __cplusplus
extern "C"
#endif
char url_init ();
int
main ()
{
return url_init ();
  ;
  return 0;
}
_ACEOF
if ac_fn_cxx_try_link "$LINENO"; then :
  ac_cv_lib_urlmatch_url_init=yes
else
  ac_cv_lib_urlmatch_url_init=no
fi
rm -f core conftest.err conftest.$ac_objext \
    conftest$ac_exeext conftest.$ac_ext
LIBS=$ac_check_lib_save_LIBS
fi
{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $ac_cv_lib_urlmatch_url_init" >&5
$as_echo "$ac_cv_lib_urlmatch_url_init" >&6; }
if test "x$ac_cv_lib_urlmatch_url_init" = xyes; then :
  cat >>confdefs.h <<_ACEOF
#define HAVE_LIBURLMATCH 1
_ACEOF

  LIBS="-lurlmatch $LIBS"

else
  as_fn_error $? "liburlmatch not found" "$LINENO" 5
fi

**Comment by clbr** [comment]
Okay, the lib was correctly installed, but for some reason configure
can't find it. Look in fifth's config.log, search for urlmatch and
paste the relevant lines.

**Comment by sergiall** [comment]
In config.log file in fifth's build folder I found this about urlmatch

configure:5357: checking for url_init in -lurlmatch
configure:5382: g++ -o conftest -march=native -O2 -pipe -fomit-frame-pointer -pthread  -isystem /usr/include/cairo -isystem /usr/include/glib-2.0 -isystem /usr/lib/i386-linux-gnu/glib-2.0/include -isystem /usr/include/pixman-1 -isystem /usr/include/freetype2 -isystem /usr/include/libpng12 -isystem /usr/include/freetype2 -isystem /usr/include/cairo -isystem /usr/include/glib-2.0 -isystem /usr/lib/i386-linux-gnu/glib-2.0/include -isystem /usr/include/pixman-1 -isystem /usr/include/freetype2 -isystem /usr/include/libpng12 -fvisibility-inlines-hidden  -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_THREAD_SAFE -D_REENTRANT   -lz conftest.cpp -lurlmatch    -Wl,-Bsymbolic-functions -lfltk_images -lfltk -lX11 >&5
/usr/lib/gcc/i686-linux-gnu/6/../../../../lib/liburlmatch.a(opti_init.o): In function `url_init_file2':
opti_init.c:(.text+0xa7c): undefined reference to `uncompress'
collect2: error: ld returned 1 exit status
configure:5382: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "Fifth"
| #define PACKAGE_TARNAME "fifth"
| #define PACKAGE_VERSION "0.5"
| #define PACKAGE_STRING "Fifth 0.5"
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| #define PACKAGE "fifth"
| #define VERSION "0.5"
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define __EXTENSIONS__ 1
| #define _ALL_SOURCE 1
| #define _GNU_SOURCE 1
| #define _POSIX_PTHREAD_SEMANTICS 1
| #define _TANDEM_SOURCE 1
| #define HAVE_PTHREAD_PRIO_INHERIT 1
| #define HAVE_PTHREAD 1
| /* end confdefs.h.  */
| 
| /* Override any GCC internal prototype to avoid an error.
|    Use char because int might match the return type of a GCC
|    builtin and then its argument prototype would still apply.  */
| #ifdef __cplusplus
| extern "C"
| #endif
| char url_init ();
| int
| main ()
| {
| return url_init ();
|   ;
|   return 0;
| }
configure:5391: result: no
configure:5401: error: liburlmatch not found

**Comment by sergiall** [comment]
This is full config.log
[config.log.txt](https://github.com/clbr/fifth/files/218645/config.log.txt)

**Comment by clbr** [comment]
I see, thanks. New versions are stricter about lib order.

Please edit configure, change the line
```
LIBS="-lurlmatch $LIBS"
```
into
```
LIBS="-lurlmatch $LIBS -lz"
```

Then re-run configure. This should allow urlmatch to be detected.

**Comment by clbr** [comment]
Pushed a fix.

**Comment by sergiall** [comment]
I edit the configure file as you propose,but get same error again 
This is new config.log file
[config.log.txt](https://github.com/clbr/fifth/files/218670/config.log.txt)

As I can see, the trouble in the line
opti_init.c:(.text+0xa7c): undefined reference to `uncompress' ...

**Comment by sergiall** [comment]
I'm going to make git pull ...

**Comment by sergiall** [comment]
Now I upgrade the fifth's build tree with 'git pull' command,and after re-run the './autogen' command issue with liburlmatch error was solved.Great Thanks for you!
