### ISSUE TITLE
Build problem on GuixSD

### ISSUE THREAD

**Issue by vincent-legoll** [clbr/fifth#23]
Hello,

I'm trying to package fifth for the GuixSD distribution

it's failing at ./configure not finding urlmatch:

    checking for url_init in -lurlmatch... no
    configure: error: liburlmatch not found
    phase `configure' failed after 3.2 seconds

How can I instruct the configure script where to find liburlmatch.a ?

I tried the obvious LDFLAGS (with and without the added LIBS):

[...]

    configure flags: ("CONFIG_SHELL=/gnu/store/ykzwykkvr2c80rw4l1qh3mvfdkl7jibi-bash-4.3.42/bin/bash" "SHELL=/gnu/store/ykzwykkvr2c80rw4l1qh3mvfdkl7jibi-bash-4.3.42/bin/bash" "--prefix=/gnu/store/vppc48x56mhsixvcwf2h4hkps49ag4yr-fifth-0.5" "--enable-fast-install" "--build=x86_64-unknown-linux-gnu" "LDFLAGS=-L/gnu/store/gsp3fqgmdhlay7k3cfbi5cgp3w7abvd8-urlmatch-1.0/lib" "LIBS=-lurlmatch")

[...]

and the .a is there:

    ls /gnu/store/gsp3fqgmdhlay7k3cfbi5cgp3w7abvd8-urlmatch-1.0/lib
    liburlmatch.a

    $ cp /gnu/store/gsp3fqgmdhlay7k3cfbi5cgp3w7abvd8-urlmatch-1.0/lib/liburlmatch.a .
    $ ar x liburlmatch.a 
    $ nm *.o | grep url_init
    00000000000002a0 T url_init
    0000000000000ca0 T url_init_file
    0000000000000960 T url_init_file2

**Comment by clbr** [comment]
Please check in your config.log what exactly failed.

**Comment by vincent-legoll** [comment]
Argh, looks like it needs libXft & libXfixes for the liburlmatch test to succeed...

configure:5511: checking for url_init in -lurlmatch
configure:5546: g++ -o conftest -g -O2 -pthread -isystem /gnu/store/77sab525zgknqk1pyxsb8zyp1m3y6byc-fltk-1.3.3/include -isystem /gnu/store/qxak8dv68cmrxj590r8db2g34bnnsdag-free
type-2.6.3/include/freetype2 -fvisibility-inlines-hidden -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_THREAD_SAFE -D_REENTRANT  -L/gnu/store/gsp3fqgmdhlay7k3cfbi5cgp3w7abvd8-url
match-1.0/lib -lz conftest.cpp -lurlmatch   -lurlmatch -L/gnu/store/77sab525zgknqk1pyxsb8zyp1m3y6byc-fltk-1.3.3/lib -Wl,-rpath,/gnu/store/77sab525zgknqk1pyxsb8zyp1m3y6byc-fltk-1
.3.3/lib -lfltk_images -L/gnu/store/36s16c5s9c702vzm9q6g9idc7fvds2ks-libpng-1.5.26/lib -lpng -L/gnu/store/5992iq1v7arqa14ym3di58n4la0893nv-zlib-1.2.8/lib -lz -L/gnu/store/pq0ca5
jrdwnd8y78yx0iimjqimalysxf-libjpeg-8d/lib -ljpeg -lfltk -lXfixes -lXext -lXft -lfontconfig -lpthread -ldl -lm -lX11 >&5
ld: cannot find -lXfixes
ld: cannot find -lXft
collect2: error: ld returned 1 exit status

So LDFLAGS worked...
